version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "honojs-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1v0frvxbcthr"
s3_prefix = "honojs-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
