version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "honojs-lambda"
s3_prefix = "honojs-lambda"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
disable_rollback = true
